version: '3.8'

services:
  # Development environment
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-web-dev
    ports:
      - "8001:5000"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    networks:
      - resume-network

  # Production environment (commented by default)
  # web-prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prod
  #   container_name: resume-web-prod
  #   ports:
  #     - "80:5000"
  #   environment:
  #     - FLASK_ENV=production
  #   restart: unless-stopped
  #   networks:
  #     - resume-network

  # Nginx reverse proxy (optional, for production)
  # nginx:
  #   image: nginx:alpine
  #   container_name: resume-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - web-prod
  #   restart: unless-stopped
  #   networks:
  #     - resume-network

networks:
  resume-network:
    driver: bridge

volumes:
  resume_data:
    driver: local
